### ISSUE TITLE
Instructions/binary releases for macOS

### ISSUE THREAD

**Issue by petemoore** [stripwax/SAASound#12]
Hey @stripwax this looks really great! The release binary seemed to be Windows only, so I wondered if it might be possible to make macOS release/instructions too?

Many thanks!

**Comment by stripwax** [comment]
Correct, the release binary is Windows only.  I don't have a mac, so I cannot build macOS.  At least, I don't think I can.  What would you use a macOS binary for, out of interest?  Are you familiar with CMake / can you try looking through the cmake (in particular CMakeLists.txt) and see if the build instructions make any sense or work for you?

@simonowen  -  any pointers or tips here?  :-)

**Comment by stefandrissen** [comment]
travisci offers free build services - also for macOS. 
I use them to test pyz80 and build the sam mod player dsk release.

https://travis-ci.org/stefandrissen

You just need to create an account, create an API key in github, use that in travisci and add a .travis.yml file describing your build requirement.

**Comment by simonowen** [comment]
@petemoore : Building yourself should be fairly straight-forward with CMake, which has a GUI version for macOS.  You point it at the SAASound sources directory, optionally set a build option to tell it you want a macOS ,framework rather than traditional Unix-style .so library, click the Configure button and then Build. That's all from memory though, but it should be pretty close to that.

Or if you have a console version of CMake handy you can use: `cmake -DBUILD_FRAMEWORK=ON .`

Alternatively, the macOS version of SimCoupe has a SAASound.framework within the app bundle, which shouldn't be too different from current code.  I can also build a fresh version from current source tonight, just in case. Though like @stefandrissen said, it would be good to have this project build a nightly version automatically -- something @stripwax will have to set up.

**Comment by simonowen** [comment]
Here's a fresh [macOS framework](https://home.simonowen.com/SAASound.framework-20190802.zip) build from current sources.

The CMake instructions weren't too far off from what I wrote above.  I selected the source directory, then an working output directory, and clicked Configure.  I checked the option to build a Framework and clicked Generate.  I picked the Unix-style Makefile for my generated build environment, and from a Terminal window in the output directory (above) I issued `make` to build the framework,

**Comment by stripwax** [comment]
Marking as resolved, but @petemoore feel free to reopen if the above information has not helped you.

**Comment by petemoore** [comment]
Many thanks! I'm afraid I had forgotten about this issue, so hadn't seen the responses from @simonowen and @stefandrissen. Thank you both for your help and support. I'll have a play with the binary version provided by Simon above.

I wonder if it is worth adding [the mac binary](https://home.simonowen.com/SAASound.framework-20190802.zip) to https://github.com/stripwax/SAASound/releases/tag/3.4_latest?

**Comment by stripwax** [comment]
Hi @petemoore and @simonowen .  I've been plugging away with a bunch of features for a while, so rather than rely on Simon to build a binary, I've finally hooked up the CMake pipeline on Github.  It's currently only on my latest branch ("configfile_impl"), not on master branch yet, but please take a look.  I've had Windows builds running successfully for a short while and just gotten the Ubuntu build to complete.  (untested of course).
The MacOS build failed however.  Maybe something trivial.  But if I can get this fixed then I think you'll both be rather happier!  But I don't have a Mac so I might be flying blind a bit (If you can take a look and provide any suggestions also, that would be much appreciated). 

https://github.com/stripwax/SAASound/runs/1403888547

**Comment by stripwax** [comment]
Oh I figured it out, i386 is not a supported build target.  First successful cross-platform build with new featureset!
https://github.com/stripwax/SAASound/runs/1403952193

**Comment by stripwax** [comment]
Okie dokie.   Could you please let me know if the result of the build is a working MacOS dynamic library?  You should find the Development release for macos-latest here: https://github.com/stripwax/SAASound/releases

**Comment by stripwax** [comment]
Automatic bleeding-edge snapshot builds are now working across all OS builds, so I'll close this issue.  Please reopen if you have any difficulty or of course if any of these Mac binaries don't actually work on Mac.

**Comment by simonowen** [comment]
SimCoupe uses the Framework version of SAASound on macOS, so there's no quick way to drop a .dynlib into a build to try it. Frameworks are self-contained bundles that include headers and libraries, so they're convenient for both development and releases. 

Might you consider building a framework as part of the macOS snapshot? It was the default behaviour in the original CMake changes, but my repository is probably a few months out of date so that might have changed.

**Comment by stripwax** [comment]
Alright! OK. I think I'm using the CMakeLists you gave me and the default option to build Framework is set to False, but happy to switch it. And maybe it's that simple :-)
Also, if you haven't already, please take a look at some of the recent changes to SAASound , as I know you're also building your own as part of SimCoupe which is probably stale and missing some bug fixes as well as new features!

**Comment by stripwax** [comment]
Try again now?

**Comment by simonowen** [comment]
I thought this might be quick to test over the weekend, but I've had a few issues!

SimCoupe 1.0 uses SAASound.framework, but that was from a long time ago when only PPC/i386 targets existed, and the app doesn't even run on a modern 64-bit macOS. SimCoupe 1.1 versions use the internal SAASound implementation, so I can't drop a test Framework it into that version either.  I though I'd just build from current sources, but I don't currently have access to real hardware running macOS. I built one using Xcode in a VM, but the lack of GL hardware acceleration seemed to stop it launching for some reason, so I can't yet prove it's fine yet. I don't have time to debug it at the moment to see if it's the VM or something else that's the issue.

I have tested the Framework build at some point, but not very recently. If the file structure it's creating is much the same I'd assume it's still good. When I next have access to real hardware I'll give it a real test.

**Comment by stripwax** [comment]
Thanks @simonowen .  I noticed that the current SimCoupe source on github sets SAA_BUILD_FRAMEWORK to False, and sets SAA_BUILD_UNIVERSAL to True - although I don't see what uses this flag (doesn't appear elsewhere in your CMakeLists.txt in the extern/saasound folder). So it's not super clear what should (or shouldnt) work. I think you're saying there's actually no way to do a drop-in replacement of SAASound on Mac SimCoupe currently since SAASound is built and linked statically (is that what you meant by 'internal')?

@petemoore - even though the Mac binary I built for SAASound might not be compatible with SimCoupe, is the binary release that I made useful at all? (I'm guessing probably not!) . And I'm assuming @simonowen 's earlier framework build (2 Aug 2019) was useful for you... if it was, let me see if I can replicate the 32-bit x86 build using the github pipeline.

**Comment by stripwax** [comment]
@petemoore actually let's do it the other way around, which might be easier :-)   What version of SimCoupe are you running on your Mac, and what kind of Mac (and which MacOS).

**Comment by petemoore** [comment]
I had a play myself, and was able to build SimCoupe 1.1 master branch on my mac, and also SAASound master branch independently.

Then I _replaced_ the saasound from master of simcoupe with master version of SAASound, which resulted in the following local changes:

```
pmoore@pmoore-laptop:~/git/simcoupe master $ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Extern/saasound/CMakeLists.txt
	modified:   Extern/saasound/INSTALL
	modified:   Extern/saasound/LICENCE
	modified:   Extern/saasound/README
	modified:   Extern/saasound/README.MD
	modified:   Extern/saasound/include/SAASound.h
	modified:   Extern/saasound/resources/SAASound.def
	deleted:    Extern/saasound/resources/SAASound.rc.in
	modified:   Extern/saasound/src/SAAAmp.cpp
	modified:   Extern/saasound/src/SAAAmp.h
	modified:   Extern/saasound/src/SAAEnv.cpp
	modified:   Extern/saasound/src/SAAEnv.h
	modified:   Extern/saasound/src/SAAFreq.cpp
	modified:   Extern/saasound/src/SAAFreq.dat
	modified:   Extern/saasound/src/SAAFreq.h
	modified:   Extern/saasound/src/SAAImpl.cpp
	modified:   Extern/saasound/src/SAAImpl.h
	modified:   Extern/saasound/src/SAANoise.cpp
	modified:   Extern/saasound/src/SAANoise.h
	modified:   Extern/saasound/src/SAASndC.cpp
	modified:   Extern/saasound/src/SAASndC.h
	modified:   Extern/saasound/src/SAASound.cpp
	modified:   Extern/saasound/src/config.h.in
	modified:   Extern/saasound/src/resource.h
	modified:   Extern/saasound/src/types.h

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Extern/saasound/VS17/
	Extern/saasound/resources/SAASound.cfg
	Extern/saasound/src/SAAConfig.cpp
	Extern/saasound/src/SAAConfig.h
	Extern/saasound/src/SAADevice.cpp
	Extern/saasound/src/SAADevice.h
	Extern/saasound/src/defns.h
	Extern/saasound/src/minIni/
	Extern/saasound/tests/

no changes added to commit (use "git add" and/or "git commit -a")
pmoore@pmoore-laptop:~/git/simcoupe master $ 
```

I then blew away my previous `build` directory in simcoupe, reran `cmake ..` and then ran `make` which had some problems building SAA dependency:

```
pmoore@pmoore-laptop:~/git/simcoupe/build master $ make
[  3%] Built target fmt
[  4%] Building CXX object Extern/saasound/CMakeFiles/SAASound.dir/src/SAADevice.cpp.o
/Users/pmoore/git/simcoupe/Extern/saasound/src/SAADevice.cpp:72:16: error: use of undeclared identifier 'EXTERNAL_CLK_HZ'
        _SetClockRate(EXTERNAL_CLK_HZ);
                      ^
/Users/pmoore/git/simcoupe/Extern/saasound/src/SAADevice.cpp:73:17: error: use of undeclared identifier 'DEFAULT_OVERSAMPLE'
        _SetOversample(DEFAULT_OVERSAMPLE);
                       ^
2 errors generated.
make[2]: *** [Extern/saasound/CMakeFiles/SAASound.dir/src/SAADevice.cpp.o] Error 1
make[1]: *** [Extern/saasound/CMakeFiles/SAASound.dir/all] Error 2
make: *** [all] Error 2
```

Remember, that same directory built ok from the SAASound checkout:

```
$ make
Scanning dependencies of target SAASound
[  9%] Building CXX object CMakeFiles/SAASound.dir/src/SAAAmp.cpp.o
[ 18%] Building CXX object CMakeFiles/SAASound.dir/src/SAADevice.cpp.o
[ 27%] Building CXX object CMakeFiles/SAASound.dir/src/SAAEnv.cpp.o
[ 36%] Building CXX object CMakeFiles/SAASound.dir/src/SAAFreq.cpp.o
[ 45%] Building CXX object CMakeFiles/SAASound.dir/src/SAAImpl.cpp.o
[ 54%] Building CXX object CMakeFiles/SAASound.dir/src/SAANoise.cpp.o
[ 63%] Building CXX object CMakeFiles/SAASound.dir/src/SAASndC.cpp.o
[ 72%] Building CXX object CMakeFiles/SAASound.dir/src/SAASound.cpp.o
[ 81%] Building CXX object CMakeFiles/SAASound.dir/src/SAAConfig.cpp.o
[ 90%] Building C object CMakeFiles/SAASound.dir/src/minIni/minIni.c.o
[100%] Linking CXX shared library SAASound.framework/SAASound
Copying OS X content SAASound.framework/Versions/C/Headers/SAASound.h
[100%] Built target SAASound
```

I tried without success to modify values for SAASOUND_LIBRARY and SAASOUND_INCLUDE_DIR directly in the CMakeLists.txt file of simcoupe, but wasn't able to get it to work, but I don't have a good working knowledge of cmake, so wasn't quite sure how to do this.

I can share log files etc if that is useful. I suspect the error is in the way I am running things.

I'm happy to have another stab if you have an idea of what I should run. Or if we could create a PR against simcoupe with an updated embedded SAASound library, I'm happy to experiment with running cmake builds on my physical hardware here.

Regarding the original goal of getting SAASound working on my laptop, I think that is achieved since I can build it locally outside of simcoupe - although I'm not sure when I'll have many free cycles to play around with it.

Thanks guys!

**Comment by stripwax** [comment]
Could you try deleting config.h in the same folder as config.h.in and try again?

**Comment by petemoore** [comment]
Sorry for my delay in replying!

I couldn't find a directory containing both a `config.h` and a `config.h.in` either before running `cmake` for simcoupe, or afterwards.

I wrote this short script to show what I am doing, and for some reason, we get the following warning:

```
-- Using Extern/saasound
CMake Warning (dev) at Extern/saasound/CMakeLists.txt:36 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "SAASound" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

and then later on a build failure:

```
-- Configuring done
CMake Error at CMakeLists.txt:152 (add_executable):
  Cannot find source file:

    include/SAASound.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

This seems to be a step back from where I was before, not sure what I did differently, but hopefully having a script to show you should make it easier to troubleshoot.

Here is the script:

```
pmoore@pmoore-laptop:~ $ cat build.sh 
#!/bin/bash -xve

rm -rf tmp
mkdir tmp
cd tmp
git clone git@github.com:simonowen/simcoupe.git
cd simcoupe
rm -rf Extern/saasound
git clone git@github.com:stripwax/SAASound.git Extern/saasound
rm -rf Extern/saasound/.git
git status
mkdir build
cd build

find .. -name config.h
find .. -name config.h.in

cmake .. || true

find .. -name config.h
find .. -name config.h.in
```

And here is the full output:

```
pmoore@pmoore-laptop:~ $ ./build.sh 
#!/bin/bash -xve

rm -rf tmp
+ rm -rf tmp
mkdir tmp
+ mkdir tmp
cd tmp
+ cd tmp
git clone git@github.com:simonowen/simcoupe.git
+ git clone git@github.com:simonowen/simcoupe.git
Cloning into 'simcoupe'...
remote: Enumerating objects: 704, done.
remote: Counting objects: 100% (704/704), done.
remote: Compressing objects: 100% (346/346), done.
remote: Total 10193 (delta 442), reused 546 (delta 353), pack-reused 9489
Receiving objects: 100% (10193/10193), 4.56 MiB | 7.35 MiB/s, done.
Resolving deltas: 100% (7790/7790), done.
cd simcoupe
+ cd simcoupe
rm -rf Extern/saasound
+ rm -rf Extern/saasound
git clone git@github.com:stripwax/SAASound.git Extern/saasound
+ git clone git@github.com:stripwax/SAASound.git Extern/saasound
Cloning into 'Extern/saasound'...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 1129 (delta 23), reused 7 (delta 2), pack-reused 1073
Receiving objects: 100% (1129/1129), 673.06 KiB | 1.92 MiB/s, done.
Resolving deltas: 100% (671/671), done.
rm -rf Extern/saasound/.git
+ rm -rf Extern/saasound/.git
git status
+ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Extern/saasound/.gitignore
	modified:   Extern/saasound/CMakeLists.txt
	modified:   Extern/saasound/INSTALL
	modified:   Extern/saasound/LICENCE
	modified:   Extern/saasound/README
	modified:   Extern/saasound/README.MD
	modified:   Extern/saasound/include/SAASound.h
	modified:   Extern/saasound/resources/SAASound.def
	deleted:    Extern/saasound/resources/SAASound.rc.in
	modified:   Extern/saasound/src/SAAAmp.cpp
	modified:   Extern/saasound/src/SAAAmp.h
	modified:   Extern/saasound/src/SAAEnv.cpp
	modified:   Extern/saasound/src/SAAEnv.h
	modified:   Extern/saasound/src/SAAFreq.cpp
	modified:   Extern/saasound/src/SAAFreq.dat
	modified:   Extern/saasound/src/SAAFreq.h
	modified:   Extern/saasound/src/SAAImpl.cpp
	modified:   Extern/saasound/src/SAAImpl.h
	modified:   Extern/saasound/src/SAANoise.cpp
	modified:   Extern/saasound/src/SAANoise.h
	modified:   Extern/saasound/src/SAASndC.cpp
	modified:   Extern/saasound/src/SAASndC.h
	modified:   Extern/saasound/src/SAASound.cpp
	modified:   Extern/saasound/src/config.h.in
	modified:   Extern/saasound/src/resource.h
	modified:   Extern/saasound/src/types.h

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Extern/saasound/VS17/
	Extern/saasound/resources/SAASound.cfg
	Extern/saasound/src/SAAConfig.cpp
	Extern/saasound/src/SAAConfig.h
	Extern/saasound/src/SAADevice.cpp
	Extern/saasound/src/SAADevice.h
	Extern/saasound/src/defns.h
	Extern/saasound/src/minIni/
	Extern/saasound/tests/

no changes added to commit (use "git add" and/or "git commit -a")
mkdir build
+ mkdir build
cd build
+ cd build

find .. -name config.h
+ find .. -name config.h
find .. -name config.h.in
+ find .. -name config.h.in
../config.h.in
../Extern/saasound/src/config.h.in

cmake .. || true
+ cmake ..
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build back-end: auto
-- Looking for C++ include optional
-- Looking for C++ include optional - found
-- Looking for C++ include variant
-- Looking for C++ include variant - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
-- Found BZip2: /usr/lib/libbz2.dylib (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.37") 
-- Using Extern/saasound
CMake Warning (dev) at Extern/saasound/CMakeLists.txt:36 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "SAASound" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found libspectrum: /usr/local/lib/libspectrum.dylib
-- Using Extern/resid
-- xaudio2_9redist not found
-- Performing Test COMPILER_SUPPORTS_STDLIBCXX
-- Performing Test COMPILER_SUPPORTS_STDLIBCXX - Success
-- Version: 7.0.1
-- Build type: 
-- CXX_STANDARD: 11
-- Performing Test has_std_11_flag
-- Performing Test has_std_11_flag - Success
-- Performing Test has_std_0x_flag
-- Performing Test has_std_0x_flag - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Success
-- Required features: cxx_variadic_templates
-- Performing Test HAS_NULLPTR_WARNING
-- Performing Test HAS_NULLPTR_WARNING - Success
-- Looking for strtod_l
-- Looking for strtod_l - found
-- Found SDL2: /usr/local/lib/libSDL2main.a;/usr/local/lib/libSDL2.dylib;-framework Cocoa  
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework   
-- Configuring done
CMake Error at CMakeLists.txt:152 (add_executable):
  Cannot find source file:

    include/SAASound.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


-- Generating done
-- Build files have been written to: /Users/pmoore/tmp/simcoupe/build
+ true

find .. -name config.h
+ find .. -name config.h
../build/config.h
find .. -name config.h.in
+ find .. -name config.h.in
../config.h.in
../Extern/saasound/src/config.h.in
```

Do you have an idea how I could patch this script to get it to work?

Thanks Dave!

**Comment by stripwax** [comment]
Thanks for the lovely details! So, what I'll try then is compiling SimCoupe
myself (Windows or maybe even Linux / WSL) and see if I get success or see
the same errors. If I get something similar it feels like I'll be close
enough to help diagnose/fix even though I don't have access to a Mac!

**Comment by petemoore** [comment]
FWIW I get the same with Linux build under docker:

```
root@88a5323ce83c:/# ./build.sh 
#!/bin/bash -xve

rm -rf tmp
+ rm -rf tmp
mkdir tmp
+ mkdir tmp
cd tmp
+ cd tmp
git clone git@github.com:simonowen/simcoupe.git
+ git clone git@github.com:simonowen/simcoupe.git
Cloning into 'simcoupe'...
remote: Enumerating objects: 704, done.
remote: Counting objects: 100% (704/704), done.
remote: Compressing objects: 100% (346/346), done.
remote: Total 10193 (delta 442), reused 546 (delta 353), pack-reused 9489
Receiving objects: 100% (10193/10193), 4.56 MiB | 2.90 MiB/s, done.
Resolving deltas: 100% (7790/7790), done.
cd simcoupe
+ cd simcoupe
rm -rf Extern/saasound
+ rm -rf Extern/saasound
git clone git@github.com:stripwax/SAASound.git Extern/saasound
+ git clone git@github.com:stripwax/SAASound.git Extern/saasound
Cloning into 'Extern/saasound'...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 1129 (delta 23), reused 7 (delta 2), pack-reused 1073
Receiving objects: 100% (1129/1129), 673.06 KiB | 1.58 MiB/s, done.
Resolving deltas: 100% (671/671), done.
rm -rf Extern/saasound/.git
+ rm -rf Extern/saasound/.git
git status
+ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Extern/saasound/.gitignore
	modified:   Extern/saasound/CMakeLists.txt
	modified:   Extern/saasound/INSTALL
	modified:   Extern/saasound/LICENCE
	modified:   Extern/saasound/README
	modified:   Extern/saasound/README.MD
	modified:   Extern/saasound/include/SAASound.h
	modified:   Extern/saasound/resources/SAASound.def
	deleted:    Extern/saasound/resources/SAASound.rc.in
	modified:   Extern/saasound/src/SAAAmp.cpp
	modified:   Extern/saasound/src/SAAAmp.h
	modified:   Extern/saasound/src/SAAEnv.cpp
	modified:   Extern/saasound/src/SAAEnv.h
	modified:   Extern/saasound/src/SAAFreq.cpp
	modified:   Extern/saasound/src/SAAFreq.dat
	modified:   Extern/saasound/src/SAAFreq.h
	modified:   Extern/saasound/src/SAAImpl.cpp
	modified:   Extern/saasound/src/SAAImpl.h
	modified:   Extern/saasound/src/SAANoise.cpp
	modified:   Extern/saasound/src/SAANoise.h
	modified:   Extern/saasound/src/SAASndC.cpp
	modified:   Extern/saasound/src/SAASndC.h
	modified:   Extern/saasound/src/SAASound.cpp
	modified:   Extern/saasound/src/config.h.in
	modified:   Extern/saasound/src/resource.h
	modified:   Extern/saasound/src/types.h

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Extern/saasound/VS17/
	Extern/saasound/resources/SAASound.cfg
	Extern/saasound/src/SAAConfig.cpp
	Extern/saasound/src/SAAConfig.h
	Extern/saasound/src/SAADevice.cpp
	Extern/saasound/src/SAADevice.h
	Extern/saasound/src/defns.h
	Extern/saasound/src/minIni/
	Extern/saasound/tests/

no changes added to commit (use "git add" and/or "git commit -a")
mkdir build
+ mkdir build
cd build
+ cd build

find .. -name config.h
+ find .. -name config.h
find .. -name config.h.in
+ find .. -name config.h.in
../Extern/saasound/src/config.h.in
../config.h.in

cmake .. || true
+ cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build back-end: auto
-- Looking for C++ include optional
-- Looking for C++ include optional - found
-- Looking for C++ include variant
-- Looking for C++ include variant - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
-- Using Extern/saasound
CMake Warning (dev) at Extern/saasound/CMakeLists.txt:36 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "SAASound" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- libspectrum not found (no tape/snapshot support)
-- Using Extern/resid
-- xaudio2_9redist not found
-- Performing Test COMPILER_SUPPORTS_STDLIBCXX
-- Performing Test COMPILER_SUPPORTS_STDLIBCXX - Failed
-- Version: 7.0.1
-- Build type: 
-- CXX_STANDARD: 11
-- Performing Test has_std_11_flag
-- Performing Test has_std_11_flag - Success
-- Performing Test has_std_0x_flag
-- Performing Test has_std_0x_flag - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Success
-- Required features: cxx_variadic_templates
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:288 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Configuring done
CMake Error at CMakeLists.txt:152 (add_executable):
  Cannot find source file:

    include/SAASound.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
+ true

find .. -name config.h
+ find .. -name config.h
../build/config.h
find .. -name config.h.in
+ find .. -name config.h.in
../Extern/saasound/src/config.h.in
../config.h.in
```

**Comment by stripwax** [comment]
Well, if it helps (probably not), I too was able to get the same error you saw when building (the error you originally posted on 30Nov). Evidently, I don't understand how CMake and/or cmake subprojects are supposed to work.  I agree that your pull request addresses one issue but since it doesn't fix the build I won't accept it (yet) - I need to understand what's going on first.

**Comment by stripwax** [comment]
ooooooooookay .   What's happening here is that cmake is reusing the same top-level config.h for both simcoupe and saasound.  What does that mean?  It means that both simcoupe and saasound HAPPEN TO HAVE an output file named config.h (obviously different) in both of their CMakeLists.txt, and when building the saasound subproject from the simcoupe toplevel folder, it uses simcoupe's config.h when building saasound.  And of course that doesn't work, because simcoupe's config.h doesn't define EXTERNAL_CLK_HZ and DEFAULT_OVERSAMPLE .

I can't say why, exactly, why cmake doesn't use the saasound config.h.in to generate the saasound config.h - that would seem obvious to me - but cmake seems to be ignoring that step, and/or assuming that the config.h generated from the simcoupe config.h.in is somehow the right one to use for the saasound config.h ..  No idea.

You might be wondering why I'm generating config.h in the build directory rather than in the saasound src directory or include directory or something like that.  Well, that's because the github actions I'm using have a non-writeable src/including directory, whereas the build folder is writeable on /tmp .

The easiest 'quick fix' seems to be if i just rename my config.h to (say) saaconfig.h .  I'll do that.

**Comment by petemoore** [comment]
Awesome, many thanks Dave!
