### ISSUE TITLE
Too high runtime requirements in Windows

### ISSUE THREAD

**Issue by AleyCZ** [stripwax/SAASound#32]
As you know I use SaaSound in my ASCD emulator. And ASCD is built with Visual Studio 2005 so it cleanly supports all operating systems from Windows 2000 to Windows 10. (Pre-2000 versions are not supported just because my timer code uses NT-kernel. This could be rewritten to support even older systems, but that's not really needed.)

In contrast to that, your SaaSound is compiled with Visual Studio 2017 which supports only Windows Vista and above and your DLL file also depends on VCRUNTIME140.DLL file which comes from Visual Studio 2017 and it is not present by default on each machine and people needs to search internet to get it (if they don't have it already from some other program).

I assume these restrictions are not needed and they are just caused by using that particular C++ compiler. So it would be nice if you could at least recompile it with static CRT library which would remove that VCRUNTIME140.DLL dependency. (I am not sure about those older Windows, how far it is compatible or not. We can test it.)

Your DLLs are binary-compatible with older versions, exactly as you stated in documentation, but only as far as people have that dependency DLL on their computer and use a new-enough operating system. :-) So I am thinking about recompilation in an older Visual Studio, but the project files are not backward compatible and cannot be opened directly in there.

**Comment by stripwax** [comment]
You should always be able to install msvcredist (downloadable from
microsoft) and you do not need to install Visual Studio.

Having said that, I will look into a static build. The latest binary
releases are all built using github automation, and Windows 2000,etc, is
not an easy platform to obtain and I have no way of testing it, but as you
say, the statically-linked dll should work OK, assuming the application
itself is not using dynamic crt (Microsoft recommended against mixing
static and dynamic crts). This article is reasonably good, and indeed
includes the suggestion to compile from source (which you are free to do).

**Comment by stripwax** [comment]
https://www.caichinger.com/blog/2016/01/01/mixing_crt_versions/

**Comment by AleyCZ** [comment]
Thank you, I was actually able to download version 3.4.0 and easily recompile it myself with Visual Studio 2005 and static libraries. No single problem, error or warning. Very nice!

So my compiled DLL is compatible with all Windows from 95 to 10 (11 not tested :-)). And I am releasing this build with my emulator ASCD 1.2 (I am putting it online right now.) I use VS 2005 Professional, because I have a licence and it is the last version supporting really all Windows. :-)

So please consider what I proposed mainly for other users, it would allow to do easy binary replacement for any already released software using SAASound. And also it makes the downloads much smaller. :-) I could also contribute and give you the project files for VS2005, if you consider this a good thing (to include in the repository). :-)

**Comment by stripwax** [comment]
You don't have to use Visual Studio 2017; you can compile using whatever you like.  If you can contribute a recipe using CMAKE that would be ideal.  For now I will close this issue, but feel free to submit a pull request for a CMAKE recipe that compiles to a DLL that is compatible with Win95.
